"""add fraud model audit fields

Revision ID: b59fa1b63d2a
Revises: be5564fec090
Create Date: 2026-09-21 01:11:40.052159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59fa1b63d2a'
down_revision: Union[str, Sequence[str], None] = 'be5564fec090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('model_version', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('model_threshold', sa.Numeric(precision=5, scale=4), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'model_threshold')
    op.drop_column('transactions', 'model_version')
    # ### end Alembic commands ###
